using System;
using System.Collections.Generic;

namespace PathOfExile.Model
{
    public class Map : Item
    {
        public static readonly IEnumerable<String> BASES = new List<String>
        {
            "Abyss Map",
            "Academy Map",
            "Acid Lakes Map",
            "Alleyways Map",
            "Ancient City Map",
            "Arachnid Nest Map",
            "Arachnid Tomb Map",
            "Arcade Map",
            "Arena Map",
            "Arid Lake Map",
            "Armoury Map",
            "Arsenal Map",
            "Ashen Wood Map",
            "Atoll Map",
            "Barrows Map",
            "Basilica Map",
            "Bazaar Map",
            "Beach Map",
            "Beacon Map",
            "Belfry Map",
            "Bog Map",
            "Bone Crypt Map",
            "Burial Chambers Map",
            "Cage Map",
            "Caldera Map",
            "Canyon Map",
            "Carcass Map",
            "Castle Ruins Map",
            "Catacombs Map",
            "Cavern Map",
            "Cells Map",
            "Cemetery Map",
            "Channel Map",
            "Chateau Map",
            "City Square Map",
            "Colonnade Map",
            "Colosseum Map",
            "Conservatory Map",
            "Coral Ruins Map",
            "Core Map",
            "Courthouse Map",
            "Courtyard Map",
            "Coves Map",
            "Crematorium Map",
            "Crimson Temple Map",
            "Crypt Map",
            "Crystal Ore Map",
            "Cursed Crypt Map",
            "Dark Forest Map",
            "Defiled Cathedral Map",
            "Desert Map",
            "Desert Spring Map",
            "Dig Map",
            "Dunes Map",
            "Dungeon Map",
            "Estuary Map",
            "Excavation Map",
            "Factory Map",
            "Fields Map",
            "Flooded Mine Map",
            "Forge of the Phoenix Map",
            "Gardens Map",
            "Geode Map",
            "Ghetto Map",
            "Gorge Map",
            "Graveyard Map",
            "Grotto Map",
            "Harbinger Map",
            "Haunted Mansion Map",
            "High Gardens Map",
            "Iceberg Map",
            "Infested Valley Map",
            "Ivory Temple Map",
            "Jungle Valley Map",
            "Laboratory Map",
            "Lair Map",
            "Lair of the Hydra Map",
            "Lava Chamber Map",
            "Lava Lake Map",
            "Leyline Map",
            "Lighthouse Map",
            "Lookout Map",
            "Malformation Map",
            "Marshes Map",
            "Mausoleum Map",
            "Maze Map",
            "Maze of the Minotaur Map",
            "Mesa Map",
            "Mineral Pools Map",
            "Moon Temple Map",
            "Mud Geyser Map",
            "Museum Map",
            "Necropolis Map",
            "Oasis Map",
            "Orchard Map",
            "Overgrown Ruin Map",
            "Overgrown Shrine Map",
            "Palace Map",
            "Park Map",
            "Pen Map",
            "Peninsula Map",
            "Phantasmagoria Map",
            "Pier Map",
            "Pit Map",
            "Pit of the Chimera Map",
            "Plateau Map",
            "Plaza Map",
            "Port Map",
            "Precinct Map",
            "Primordial Pool Map",
            "Promenade Map",
            "Quarry Map",
            "Racecourse Map",
            "Ramparts Map",
            "Reef Map",
            "Relic Chambers Map",
            "Residence Map",
            "Scriptorium Map",
            "Sepulchre Map",
            "Sewer Map",
            "Shaped Academy Map",
            "Shaped Acid Lakes Map",
            "Shaped Arachnid Nest Map",
            "Shaped Arachnid Tomb Map",
            "Shaped Arcade Map",
            "Shaped Arena Map",
            "Shaped Arid Lake Map",
            "Shaped Armoury Map",
            "Shaped Arsenal Map",
            "Shaped Ashen Wood Map",
            "Shaped Atoll Map",
            "Shaped Barrows Map",
            "Shaped Beach Map",
            "Shaped Bog Map",
            "Shaped Burial Chambers Map",
            "Shaped Canyon Map",
            "Shaped Castle Ruins Map",
            "Shaped Catacombs Map",
            "Shaped Cavern Map",
            "Shaped Cells Map",
            "Shaped Cemetery Map",
            "Shaped Channel Map",
            "Shaped Colonnade Map",
            "Shaped Courtyard Map",
            "Shaped Coves Map",
            "Shaped Crypt Map",
            "Shaped Crystal Ore Map",
            "Shaped Desert Map",
            "Shaped Dunes Map",
            "Shaped Dungeon Map",
            "Shaped Factory Map",
            "Shaped Ghetto Map",
            "Shaped Graveyard Map",
            "Shaped Grotto Map",
            "Shaped Jungle Valley Map",
            "Shaped Malformation Map",
            "Shaped Marshes Map",
            "Shaped Mesa Map",
            "Shaped Mud Geyser Map",
            "Shaped Museum Map",
            "Shaped Oasis Map",
            "Shaped Orchard Map",
            "Shaped Overgrown Shrine Map",
            "Shaped Peninsula Map",
            "Shaped Phantasmagoria Map",
            "Shaped Pier Map",
            "Shaped Pit Map",
            "Shaped Port Map",
            "Shaped Primordial Pool Map",
            "Shaped Promenade Map",
            "Shaped Quarry Map",
            "Shaped Racecourse Map",
            "Shaped Ramparts Map",
            "Shaped Reef Map",
            "Shaped Sewer Map",
            "Shaped Shore Map",
            "Shaped Spider Forest Map",
            "Shaped Spider Lair Map",
            "Shaped Strand Map",
            "Shaped Temple Map",
            "Shaped Terrace Map",
            "Shaped Thicket Map",
            "Shaped Tower Map",
            "Shaped Tropical Island Map",
            "Shaped Underground River Map",
            "Shaped Vaal City Map",
            "Shaped Vaal Pyramid Map",
            "Shaped Vault Map",
            "Shaped Villa Map",
            "Shaped Waste Pool Map",
            "Shaped Wharf Map",
            "Shipyard Map",
            "Shore Map",
            "Shrine Map",
            "Siege Map",
            "Spider Forest Map",
            "Spider Lair Map",
            "Springs Map",
            "Strand Map",
            "Sulphur Vents Map",
            "Sulphur Wastes Map",
            "Summit Map",
            "Sunken City Map",
            "Temple Map",
            "Terrace Map",
            "Thicket Map",
            "Torture Chamber Map",
            "Tower Map",
            "Toxic Sewer Map",
            "Tribunal Map",
            "Tropical Island Map",
            "Underground River Map",
            "Underground Sea Map",
            "Vaal City Map",
            "Vaal Pyramid Map",
            "Vaal Temple Map",
            "Vault Map",
            "Villa Map",
            "Volcano Map",
            "Waste Pool Map",
            "Wasteland Map",
            "Waterways Map",
            "Wharf Map"
        };

        public IEnumerable<Property> properties { get; set; }
        public IEnumerable<string> explicitMods { get; set; }
        public string descrText { get; set; }
        public IEnumerable<string> flavourText { get; set; }
        public string inventoryId { get; set; }
        public Category category { get; set; }

        public class Category
        {
            public List<object> maps { get; set; }
        }
    }
}