using System;
using System.Collections.Generic;

namespace PoEPublicStash.Model
{
    public class Gem : SocketableItem
    {
        public static readonly IEnumerable<String> BASES = new List<String>
        {
            "Abyssal Cry",
            "Added Chaos Damage Support",
            "Added Cold Damage Support",
            "Added Fire Damage Support",
            "Added Lightning Damage Support",
            "Additional Accuracy Support",
            "Ancestral Call Support",
            "Ancestral Protector",
            "Ancestral Warchief",
            "Anger",
            "Animate Guardian",
            "Animate Weapon",
            "Arc",
            "Arcane Surge Support",
            "Arctic Armour",
            "Arctic Breath",
            "Assassin's Mark",
            "Ball Lightning",
            "Barrage",
            "Bear Trap",
            "Blade Flurry",
            "Blade Vortex",
            "Bladefall",
            "Blasphemy Support",
            "Blast Rain",
            "Blight",
            "Blind Support",
            "Blink Arrow",
            "Block Chance Reduction Support",
            "Blood Magic Support",
            "Blood Rage",
            "Bloodlust Support",
            "Bodyswap",
            "Bone Offering",
            "Brutality Support",
            "Burning Arrow",
            "Burning Damage Support",
            "Cast On Critical Strike Support",
            "Cast on Death Support",
            "Cast on Melee Kill Support",
            "Cast when Damage Taken Support",
            "Cast when Stunned Support",
            "Cast while Channelling Support",
            "Caustic Arrow",
            "Chain Support",
            "Chance to Bleed Support",
            "Chance to Flee Support",
            "Chance to Ignite Support",
            "Charged Dash",
            "Clarity",
            "Cleave",
            "Cluster Traps Support",
            "Cold Penetration Support",
            "Cold Snap",
            "Cold to Fire Support",
            "Concentrated Effect Support",
            "Conductivity",
            "Contagion",
            "Controlled Destruction Support",
            "Conversion Trap",
            "Convocation",
            "Cremation",
            "Culling Strike Support",
            "Curse On Hit Support",
            "Cyclone",
            "Damage on Full Life Support",
            "Dark Pact",
            "Deadly Ailments Support",
            "Decay Support",
            "Decoy Totem",
            "Desecrate",
            "Despair",
            "Determination",
            "Detonate Dead",
            "Detonate Mines",
            "Devouring Totem",
            "Discharge",
            "Discipline",
            "Dominating Blow",
            "Double Strike",
            "Dual Strike",
            "Earthquake",
            "Efficacy Support",
            "Elemental Damage with Attacks Support",
            "Elemental Focus Support",
            "Elemental Hit",
            "Elemental Proliferation Support",
            "Elemental Weakness",
            "Empower Support",
            "Endurance Charge on Melee Stun Support",
            "Enduring Cry",
            "Enfeeble",
            "Enhance Support",
            "Enlighten Support",
            "Essence Drain",
            "Ethereal Knives",
            "Explosive Arrow",
            "Faster Attacks Support",
            "Faster Casting Support",
            "Faster Projectiles Support",
            "Fire Nova Mine",
            "Fire Penetration Support",
            "Fire Trap",
            "Fireball",
            "Firestorm",
            "Flame Dash",
            "Flame Surge",
            "Flame Totem",
            "Flameblast",
            "Flammability",
            "Flesh Offering",
            "Flicker Strike",
            "Fork Support",
            "Fortify Support",
            "Freeze Mine",
            "Freezing Pulse",
            "Frenzy",
            "Frost Blades",
            "Frost Bomb",
            "Frost Wall",
            "Frostbite",
            "Frostbolt",
            "Generosity Support",
            "Glacial Cascade",
            "Glacial Hammer",
            "Grace",
            "Greater Multiple Projectiles Support",
            "Ground Slam",
            "Haste",
            "Hatred",
            "Heavy Strike",
            "Herald of Ash",
            "Herald of Ice",
            "Herald of Thunder",
            "Hypothermia Support",
            "Ice Bite Support",
            "Ice Crash",
            "Ice Nova",
            "Ice Shot",
            "Ice Spear",
            "Ice Trap",
            "Ignite Proliferation Support",
            "Immolate Support",
            "Immortal Call",
            "Incinerate",
            "Increased Area of Effect Support",
            "Increased Critical Damage Support",
            "Increased Critical Strikes Support",
            "Increased Duration Support",
            "Infernal Blow",
            "Innervate Support",
            "Iron Grip Support",
            "Iron Will Support",
            "Item Quantity Support",
            "Item Rarity Support",
            "Kinetic Blast",
            "Knockback Support",
            "Lacerate",
            "Leap Slam",
            "Less Duration Support",
            "Lesser Multiple Projectiles Support",
            "Lesser Poison Support",
            "Life Gain on Hit Support",
            "Life Leech Support",
            "Lightning Arrow",
            "Lightning Penetration Support",
            "Lightning Strike",
            "Lightning Tendrils",
            "Lightning Trap",
            "Lightning Warp",
            "Magma Orb",
            "Maim Support",
            "Mana Leech Support",
            "Melee Physical Damage Support",
            "Melee Splash Support",
            "Minefield Support",
            "Minion Damage Support",
            "Minion Life Support",
            "Minion Speed Support",
            "Minion and Totem Elemental Resistance Support",
            "Mirage Archer Support",
            "Mirror Arrow",
            "Molten Shell",
            "Molten Strike",
            "Multiple Traps Support",
            "Multistrike Support",
            "Onslaught Support",
            "Orb of Storms",
            "Phase Run",
            "Physical Projectile Attack Damage Support",
            "Physical to Lightning Support",
            "Pierce Support",
            "Poacher's Mark",
            "Point Blank Support",
            "Poison Support",
            "Portal",
            "Power Charge On Critical Support",
            "Power Siphon",
            "Projectile Weakness",
            "Puncture",
            "Punishment",
            "Purity of Elements",
            "Purity of Fire",
            "Purity of Ice",
            "Purity of Lightning",
            "Rain of Arrows",
            "Raise Spectre",
            "Raise Zombie",
            "Rallying Cry",
            "Ranged Attack Totem Support",
            "Reave",
            "Reckoning",
            "Reduced Mana Support",
            "Rejuvenation Totem",
            "Remote Mine Support",
            "Righteous Fire",
            "Riposte",
            "Ruthless Support",
            "Scorching Ray",
            "Searing Bond",
            "Shield Charge",
            "Shock Nova",
            "Shockwave Totem",
            "Shrapnel Shot",
            "Siege Ballista",
            "Slower Projectiles Support",
            "Smoke Mine",
            "Spark",
            "Spectral Throw",
            "Spell Cascade Support",
            "Spell Echo Support",
            "Spell Totem Support",
            "Spirit Offering",
            "Split Arrow",
            "Static Strike",
            "Storm Barrier Support",
            "Storm Burst",
            "Storm Call",
            "Stun Support",
            "Summon Chaos Golem",
            "Summon Flame Golem",
            "Summon Ice Golem",
            "Summon Lightning Golem",
            "Summon Raging Spirit",
            "Summon Skeleton",
            "Summon Stone Golem",
            "Sunder",
            "Sweep",
            "Swift Affliction Support",
            "Tempest Shield",
            "Temporal Chains",
            "Tornado Shot",
            "Trap Support",
            "Trap Cooldown Support",
            "Trap and Mine Damage Support",
            "Unbound Ailments Support",
            "Unearth",
            "Vaal Arc",
            "Vaal Breach",
            "Vaal Burning Arrow",
            "Vaal Clarity",
            "Vaal Cold Snap",
            "Vaal Cyclone",
            "Vaal Detonate Dead",
            "Vaal Discipline",
            "Vaal Double Strike",
            "Vaal Fireball",
            "Vaal Flameblast",
            "Vaal Glacial Hammer",
            "Vaal Grace",
            "Vaal Ground Slam",
            "Vaal Haste",
            "Vaal Ice Nova",
            "Vaal Immortal Call",
            "Vaal Lightning Strike",
            "Vaal Lightning Trap",
            "Vaal Lightning Warp",
            "Vaal Molten Shell",
            "Vaal Power Siphon",
            "Vaal Rain of Arrows",
            "Vaal Reave",
            "Vaal Righteous Fire",
            "Vaal Spark",
            "Vaal Spectral Throw",
            "Vaal Storm Call",
            "Vaal Summon Skeletons",
            "Vengeance",
            "Vigilant Strike",
            "Vile Toxins Support",
            "Viper Strike",
            "Vitality",
            "Void Manipulation Support",
            "Volatile Dead",
            "Volley Support",
            "Vortex",
            "Vulnerability",
            "Warlord's Mark",
            "Whirling Blades",
            "Wild Strike",
            "Wither",
            "Wrath",
        };

        public bool verified { get; set; }
        public int w { get; set; }
        public int h { get; set; }
        public int ilvl { get; set; }
        public string icon { get; set; }
        public bool support { get; set; }
        public string league { get; set; }
        public string id { get; set; }
        public string name { get; set; }
        public bool identified { get; set; }
        public IEnumerable<Property> properties { get; set; }
        public IEnumerable<AdditionalProperty> additionalProperties { get; set; }
        public IEnumerable<Requirement> requirements { get; set; }
        public string secDescrText { get; set; }
        public IEnumerable<string> explicitMods { get; set; }
        public string descrText { get; set; }
        public int frameType { get; set; }
        public string category { get; set; }
        public int x { get; set; }
        public int y { get; set; }
        public string inventoryId { get; set; }
    }
}