using System;
using System.Collections.Generic;

namespace PathOfExile.Model
{
    public class Chest : Armour
    {
        public static readonly IEnumerable<String> BASES = new List<String>
        {
            "Arena Plate",
            "Assassin's Garb",
            "Astral Plate",
            "Battle Lamellar",
            "Battle Plate",
            "Blood Raiment",
            "Bone Armour",
            "Bronze Plate",
            "Buckskin Tunic",
            "Cabalist Regalia",
            "Carnal Armour",
            "Chain Hauberk",
            "Chainmail Doublet",
            "Chainmail Tunic",
            "Chainmail Vest",
            "Chestplate",
            "Colosseum Plate",
            "Commander's Brigandine",
            "Conjurer's Vestment",
            "Conquest Chainmail",
            "Copper Plate",
            "Coronal Leather",
            "Crimson Raiment",
            "Crusader Chainmail",
            "Crusader Plate",
            "Crypt Armour",
            "Cutthroat's Garb",
            "Desert Brigandine",
            "Destiny Leather",
            "Destroyer Regalia",
            "Devout Chainmail",
            "Dragonscale Doublet",
            "Eelskin Tunic",
            "Elegant Ringmail",
            "Exquisite Leather",
            "Field Lamellar",
            "Frontier Leather",
            "Full Chainmail",
            "Full Dragonscale",
            "Full Leather",
            "Full Plate",
            "Full Ringmail",
            "Full Scale Armour",
            "Full Wyrmscale",
            "General's Brigandine",
            "Gladiator Plate",
            "Glorious Leather",
            "Glorious Plate",
            "Golden Mantle",
            "Golden Plate",
            "Holy Chainmail",
            "Hussar Brigandine",
            "Infantry Brigandine",
            "Lacquered Garb",
            "Latticed Ringmail",
            "Light Brigandine",
            "Lordly Plate",
            "Loricated Ringmail",
            "Mage's Vestment",
            "Majestic Plate",
            "Necromancer Silks",
            "Occultist's Vestment",
            "Oiled Coat",
            "Oiled Vest",
            "Ornate Ringmail",
            "Padded Jacket",
            "Padded Vest",
            "Plate Vest",
            "Quilted Jacket",
            "Ringmail Coat",
            "Sacrificial Garb",
            "Sadist Garb",
            "Sage's Robe",
            "Saint's Hauberk",
            "Saintly Chainmail",
            "Savant's Robe",
            "Scale Doublet",
            "Scale Vest",
            "Scarlet Raiment",
            "Scholar's Robe",
            "Sentinel Jacket",
            "Shabby Jerkin",
            "Sharkskin Tunic",
            "Silk Robe",
            "Silken Garb",
            "Silken Vest",
            "Silken Wrap",
            "Simple Robe",
            "Sleek Coat",
            "Soldier's Brigandine",
            "Spidersilk Robe",
            "Strapped Leather",
            "Sun Leather",
            "Sun Plate",
            "Thief's Garb",
            "Triumphant Lamellar",
            "Vaal Regalia",
            "Varnished Coat",
            "War Plate",
            "Waxed Garb",
            "Widowsilk Robe",
            "Wild Leather",
            "Wyrmscale Doublet",
            "Zodiac Leather"
        };
    }
}