using System;
using System.Collections.Generic;

namespace PathOfExile.Model
{
    public class Helmet : Armour
    {
        public static readonly IEnumerable<String> BASES = new List<String>
        {
            "Aventail Helmet",
            "Barbute Helmet",
            "Battered Helm",
            "Bone Circlet",
            "Bone Helmet",
            "Callous Mask",
            "Close Helmet",
            "Cone Helmet",
            "Crusader Helmet",
            "Deicide Mask",
            "Eternal Burgonet",
            "Ezomyte Burgonet",
            "Fencer Helm",
            "Festival Mask",
            "Fluted Bascinet",
            "Gilded Sallet",
            "Gladiator Helmet",
            "Golden Mask",
            "Golden Wreath",
            "Great Crown",
            "Great Helmet",
            "Harlequin Mask",
            "Hubris Circlet",
            "Hunter Hood",
            "Iron Circlet",
            "Iron Hat",
            "Iron Mask",
            "Lacquered Helmet",
            "Leather Cap",
            "Leather Hood",
            "Lion Pelt",
            "Lunaris Circlet",
            "Magistrate Crown",
            "Mind Cage",
            "Necromancer Circlet",
            "Nightmare Bascinet",
            "Noble Tricorne",
            "Pig-Faced Bascinet",
            "Plague Mask",
            "Praetor Crown",
            "Prophet Crown",
            "Raven Mask",
            "Reaver Helmet",
            "Regicide Mask",
            "Royal Burgonet",
            "Rusted Coif",
            "Sallet",
            "Samite Helmet",
            "Scare Mask",
            "Secutor Helm",
            "Siege Helmet",
            "Silken Hood",
            "Sinner Tricorne",
            "Solaris Circlet",
            "Soldier Helmet",
            "Steel Circlet",
            "Torture Cage",
            "Tribal Circlet",
            "Tricorne",
            "Ursine Pelt",
            "Vaal Mask",
            "Vine Circlet",
            "Visored Sallet",
            "Wolf Pelt",
            "Zealot Helmet",

        };
    }
}
