using System;
using System.Collections.Generic;

namespace PublicStash.Model
{
    internal class Shield : Armour
    {
        public static readonly IEnumerable<String> BASES = new List<String>
        {
            "Alder Spiked Shield",
            "Alloyed Spiked Shield",
            "Ancient Spirit Shield",
            "Angelic Kite Shield",
            "Archon Kite Shield",
            "Baroque Round Shield",
            "Battle Buckler",
            "Bone Spirit Shield",
            "Branded Kite Shield",
            "Brass Spirit Shield",
            "Bronze Tower Shield",
            "Buckskin Tower Shield",
            "Burnished Spiked Shield",
            "Cardinal Round Shield",
            "Cedar Tower Shield",
            "Ceremonial Kite Shield",
            "Champion Kite Shield",
            "Chiming Spirit Shield",
            "Colossal Tower Shield",
            "Compound Spiked Shield",
            "Copper Tower Shield",
            "Corroded Tower Shield",
            "Corrugated Buckler",
            "Crested Tower Shield",
            "Crimson Round Shield",
            "Crusader Buckler",
            "Driftwood Spiked Shield",
            "Ebony Tower Shield",
            "Elegant Round Shield",
            "Enameled Buckler",
            "Etched Kite Shield",
            "Ezomyte Spiked Shield",
            "Ezomyte Tower Shield",
            "Fir Round Shield",
            "Fossilised Spirit Shield",
            "Gilded Buckler",
            "Girded Tower Shield",
            "Goathide Buckler",
            "Golden Buckler",
            "Hammered Buckler",
            "Harmonic Spirit Shield",
            "Imperial Buckler",
            "Ironwood Buckler",
            "Ivory Spirit Shield",
            "Jingling Spirit Shield",
            "Lacewood Spirit Shield",
            "Lacquered Buckler",
            "Laminated Kite Shield",
            "Layered Kite Shield",
            "Linden Kite Shield",
            "Mahogany Tower Shield",
            "Maple Round Shield",
            "Mirrored Spiked Shield",
            "Mosaic Kite Shield",
            "Oak Buckler",
            "Ornate Spiked Shield",
            "Painted Buckler",
            "Painted Tower Shield",
            "Pine Buckler",
            "Pinnacle Tower Shield",
            "Plank Kite Shield",
            "Polished Spiked Shield",
            "Rawhide Tower Shield",
            "Redwood Spiked Shield",
            "Reinforced Kite Shield",
            "Reinforced Tower Shield",
            "Rotted Round Shield",
            "Scarlet Round Shield",
            "Shagreen Tower Shield",
            "Sovereign Spiked Shield",
            "Spiked Bundle",
            "Spiked Round Shield",
            "Spiny Round Shield",
            "Splendid Round Shield",
            "Splintered Tower Shield",
            "Steel Kite Shield",
            "Studded Round Shield",
            "Supreme Spiked Shield",
            "Tarnished Spirit Shield",
            "Teak Round Shield",
            "Thorium Spirit Shield",
            "Titanium Spirit Shield",
            "Twig Spirit Shield",
            "Vaal Buckler",
            "Vaal Spirit Shield",
            "Walnut Spirit Shield",
            "War Buckler",
            "Yew Spirit Shield",
        };
    }
}